const data = {
  products: [
    {
      name: "Center Table",
      slug: "center-table",
      category: "Tables",
      image: "/images/CENTER TABLE SMALL.jpg",
      price: 17000,
      brand: "Mr. Furniture",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular center table design",
    },
    {
      name: "Center Table",
      slug: "center-table",
      category: "Tables",
      image: "/images/CENTER TABLE.jpg",
      price: 12000,
      brand: "Mr. Furniture",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "Simple vintage table",
    },
    {
      name: "Wooden Chair",
      slug: "wooden-chair",
      category: "Chairs",
      image: "/images/CHAIR.jpg",
      price: 25000,
      brand: "Mr. Furniture",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "Soft foamic comfortable wooden chair",
    },
    {
      name: "Wooden Chair",
      slug: "wooden-chair",
      category: "Chairs",
      image: "/images/CHAIR1.jpg",
      price: 28000,
      brand: "Mr. Furniture",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "Soft foamic comfortable wooden chair",
    },
    {
      name: "Dining Table",
      slug: "dining-table",
      category: "Tables",
      image: "/images/DINIG TABLE.jpg",
      price: 98000,
      brand: "Mr. Furniture",
      rating: 4.8,
      numReviews: 13,
      countInStock: 20,
      description: "One is the thousand Dining Table",
    },
    {
      name: "Single Bed",
      slug: "single-bed",
      category: "Beds",
      image: "/images/SINGLE BED.jpg",
      price: 75000,
      brand: "Mr. Furniture",
      rating: 3.9,
      numReviews: 7,
      countInStock: 1,
      description: "Beautiful Handmade single bed without cusioning",
    },
    {
      name: "TV Lounge Sofa",
      slug: "tv-lounge-sofa",
      category: "Sofas",
      image: "/images/SOFA TV LOUNGE.jpg",
      price: 150000,
      brand: "Mr. Furniture",
      rating: 4.4,
      numReviews: 14,
      countInStock: 2,
      description: "Sofa for the whole family",
    },
  ],
};

export default data;
